"""Rule-based insight cards attached to fixtures.

Insights are generated by services/insights/* rules from already-stored
season stats + fixture history. Storing them lets us rank, dedupe, and
return them with the match preview in a single query.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Optional
from uuid import UUID

from sqlalchemy import BigInteger, DateTime, ForeignKey, Index, Numeric, SmallInteger, String, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class FixtureInsight(Base):
    __tablename__ = "fixture_insights"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    fixture_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("fixtures.id", ondelete="CASCADE")
    )
    rule_code: Mapped[str] = mapped_column(String)
    severity: Mapped[int] = mapped_column(SmallInteger, default=1)
    locale: Mapped[str] = mapped_column(String, default="en")
    headline: Mapped[str] = mapped_column(String)
    body: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    metric_key: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    metric_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(8, 2), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    __table_args__ = (
        Index("idx_fixture_insights_fixture", "fixture_id", "severity"),
        UniqueConstraint("fixture_id", "rule_code", "locale", name="uniq_fixture_insights_dedupe"),
    )
