"""init

Revision ID: a494312938fb
Revises: 
Create Date: 2026-05-11 02:29:31.491686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a494312938fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('first_seen_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referees_name_normalized'), 'referees', ['name_normalized'], unique=True)
    op.create_table('refresh_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_kind', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_log_entity', 'refresh_log', ['entity_kind', 'entity_id', 'finished_at'], unique=False)
    op.create_index('idx_refresh_log_status', 'refresh_log', ['status', 'started_at'], unique=False)
    op.create_table('sports',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rc_entitlement', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default_popular', sa.Boolean(), nullable=False),
    sa.Column('is_free_tier', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leagues_country_sort', 'leagues', ['country', 'sort_order'], unique=False)
    op.create_index('idx_leagues_sport_active', 'leagues', ['sport_id', 'is_active'], unique=False)
    op.create_table('referee_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('alias_normalized', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referee_aliases_ref', 'referee_aliases', ['referee_id'], unique=False)
    op.create_index(op.f('ix_referee_aliases_alias_normalized'), 'referee_aliases', ['alias_normalized'], unique=True)
    op.create_table('referee_team_history',
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('yellow_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('red_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fouls_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('last_fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('referee_id', 'team_id')
    )
    op.create_table('basketball_player_season_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('minutes_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('points_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rebounds_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assists_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steals_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocks_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('turnovers_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('two_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('two_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('two_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('three_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('three_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('three_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'team_id', 'league_id', 'season_year')
    )
    op.create_table('basketball_team_season_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('points_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('points_allowed_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('two_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('three_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('two_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('two_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('three_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('three_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_made_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_att_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rebounds_off_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rebounds_def_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rebounds_total_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assists_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steals_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocks_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('turnovers_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_played', sa.Integer(), nullable=False),
    sa.Column('home_points_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_points_allowed_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_played', sa.Integer(), nullable=False),
    sa.Column('away_points_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_points_allowed_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('total_over_2105_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spread_cover_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'league_id', 'season_year')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), sa.Computed("status IN ('FT', 'AET', 'PEN')", persisted=True), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fixtures_away_team', 'fixtures', ['away_team_id', 'kickoff_at'], unique=False)
    op.create_index('idx_fixtures_kickoff', 'fixtures', ['kickoff_at'], unique=False)
    op.create_index('idx_fixtures_league_season', 'fixtures', ['league_id', 'season_year'], unique=False)
    op.create_index('idx_fixtures_referee', 'fixtures', ['referee_id', 'kickoff_at'], unique=False)
    op.create_index('idx_fixtures_team_kickoff', 'fixtures', ['home_team_id', 'kickoff_at'], unique=False)
    op.create_table('football_player_season_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('started', sa.Integer(), nullable=False),
    sa.Column('minutes_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('shots_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shots_on_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passes_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passes_accurate_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pass_accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interceptions_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tackles_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fouls_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('was_fouled_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('yellow_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('red_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'team_id', 'league_id', 'season_year')
    )
    op.create_table('football_team_season_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('goals_for_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goals_against_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('xg_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shots_total_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shots_on_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('corners_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fouls_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('offsides_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('yellow_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('red_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('saves_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_played', sa.Integer(), nullable=False),
    sa.Column('home_goals_for_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_goals_against_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_corners_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_yellow_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_played', sa.Integer(), nullable=False),
    sa.Column('away_goals_for_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_goals_against_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_corners_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_yellow_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('over_15_hit_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('over_25_hit_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('over_35_hit_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('btts_hit_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('corners_over_85_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('corners_over_105_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cards_over_35_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cards_over_45_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'league_id', 'season_year')
    )
    op.create_table('referee_season_stats',
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('yellow_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('red_cards_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fouls_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('penalties_pg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_win_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('referee_id', 'league_id', 'season_year')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_round', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'year', name='uniq_seasons_league_year')
    )
    op.create_table('team_squads',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'player_id', 'season_year', 'league_id')
    )
    op.create_index('idx_team_squads_team_season', 'team_squads', ['team_id', 'season_year'], unique=False)
    op.create_table('basketball_fixture_team_stats',
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('field_goals_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_att', sa.Integer(), nullable=True),
    sa.Column('two_points_made', sa.Integer(), nullable=True),
    sa.Column('two_points_att', sa.Integer(), nullable=True),
    sa.Column('three_points_made', sa.Integer(), nullable=True),
    sa.Column('three_points_att', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_att', sa.Integer(), nullable=True),
    sa.Column('rebounds_offensive', sa.Integer(), nullable=True),
    sa.Column('rebounds_defensive', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('fixture_id', 'team_id')
    )
    op.create_index('idx_bfts_team', 'basketball_fixture_team_stats', ['team_id'], unique=False)
    op.create_table('fixture_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('metric_key', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'rule_code', 'locale', name='uniq_fixture_insights_dedupe')
    )
    op.create_index('idx_fixture_insights_fixture', 'fixture_insights', ['fixture_id', 'severity'], unique=False)
    op.create_table('football_fixture_team_stats',
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on', sa.Integer(), nullable=True),
    sa.Column('shots_off', sa.Integer(), nullable=True),
    sa.Column('shots_blocked', sa.Integer(), nullable=True),
    sa.Column('shots_inside_box', sa.Integer(), nullable=True),
    sa.Column('shots_outside_box', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('possession_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_accurate', sa.Integer(), nullable=True),
    sa.Column('pass_accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('xg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('fixture_id', 'team_id')
    )
    op.create_index('idx_ffts_team', 'football_fixture_team_stats', ['team_id'], unique=False)
    op.create_table('user_watchlist_fixtures',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'fixture_id')
    )
    op.create_index('idx_uwf_user_added', 'user_watchlist_fixtures', ['user_id', 'added_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uwf_user_added', table_name='user_watchlist_fixtures')
    op.drop_table('user_watchlist_fixtures')
    op.drop_index('idx_ffts_team', table_name='football_fixture_team_stats')
    op.drop_table('football_fixture_team_stats')
    op.drop_index('idx_fixture_insights_fixture', table_name='fixture_insights')
    op.drop_table('fixture_insights')
    op.drop_index('idx_bfts_team', table_name='basketball_fixture_team_stats')
    op.drop_table('basketball_fixture_team_stats')
    op.drop_index('idx_team_squads_team_season', table_name='team_squads')
    op.drop_table('team_squads')
    op.drop_table('seasons')
    op.drop_table('referee_season_stats')
    op.drop_table('football_team_season_stats')
    op.drop_table('football_player_season_stats')
    op.drop_index('idx_fixtures_team_kickoff', table_name='fixtures')
    op.drop_index('idx_fixtures_referee', table_name='fixtures')
    op.drop_index('idx_fixtures_league_season', table_name='fixtures')
    op.drop_index('idx_fixtures_kickoff', table_name='fixtures')
    op.drop_index('idx_fixtures_away_team', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('basketball_team_season_stats')
    op.drop_table('basketball_player_season_stats')
    op.drop_table('referee_team_history')
    op.drop_index(op.f('ix_referee_aliases_alias_normalized'), table_name='referee_aliases')
    op.drop_index('idx_referee_aliases_ref', table_name='referee_aliases')
    op.drop_table('referee_aliases')
    op.drop_index('idx_leagues_sport_active', table_name='leagues')
    op.drop_index('idx_leagues_country_sort', table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('sports')
    op.drop_index('idx_refresh_log_status', table_name='refresh_log')
    op.drop_index('idx_refresh_log_entity', table_name='refresh_log')
    op.drop_table('refresh_log')
    op.drop_index(op.f('ix_referees_name_normalized'), table_name='referees')
    op.drop_table('referees')
    op.drop_table('players')
    # ### end Alembic commands ###
